"""add rate field

Revision ID: 1c5c33096e79
Revises: bebb7d7511da
Create Date: 2021-08-15 19:55:03.031149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c5c33096e79'
down_revision = 'bebb7d7511da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote_model', sa.Column('rate', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quote_model', 'rate')
    # ### end Alembic commands ###
