"""add surmane

Revision ID: 3df87df5846e
Revises: 1c5c33096e79
Create Date: 2021-08-15 19:58:12.796688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3df87df5846e'
down_revision = '1c5c33096e79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author_model', sa.Column('surname', sa.String(length=32), nullable=True))
    op.create_unique_constraint(None, 'author_model', ['surname'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'author_model', type_='unique')
    op.drop_column('author_model', 'surname')
    # ### end Alembic commands ###
